name: 'Build and push platform image (arm64 or amd64)'
description: 'IQGeo reusable action to build platform specialized images for a specific architecture'

inputs:
  version:
    description: 'Platform version to build (e.g., 7.4.0)'
    required: true
    type: string
  build_id:
    description: 'Unique build ID for this workflow run'
    required: true
    type: string
  platform:
    description: 'Which OS arch to build this image on (amd64, arm64)'
    required: true
    type: string
  image_type:
    description: 'Type of platform image to build (base, build, appserver, tools, devenv, devdb-build, devdb-appserver, devdb-tools, devdb-qa-appserver)'
    required: true
    type: string
  dockerfile:
    description: 'Name of the dockerfile to use (dockerfile.base, dockerfile.build, etc.)'
    required: true
    type: string
  docker_context:
    description: 'Docker build context directory (. for platform/7x, deployment-devdb for deployment-devdb/)'
    type: string
    default: '.'
  modules:
    description: 'Comma-separated list of modules for injector images (only needed for devdb builds)'
    type: string
    required: false
  acr:
    description: 'Azure container registry server name'
    required: true
    type: string
  registry_username:
    description: 'Azure container registry username'
    required: true
    type: string
  registry_password:
    description: 'Azure container registry password'
    required: true
    type: string
  engineering_prefix:
    description: 'Engineering prefix to place images in ACR'
    type: string
    default: devops_sandbox_engineering
  gh_token:
    description: 'GitHub token to clone utils-docker-platform repo'
    required: true
    type: string
  dev_tools_version:
    description: 'Dev tools version for devenv image build (only used for devenv)'
    type: string
    required: false
  shortened_version:
    description: 'Shortened version for language packs repo'
    required: false
    type: string    
  obfuscate:
    description: 'Whether to obfuscate the platform code (unset, false, true)'
    type: string
    default: 'unset'
  platform_base:
    description: 'Platform base image name to use (platform/platform-base or platform/platform-base-clear)'
    type: string
    default: 'platform/platform-base'

runs:
  using: "composite"
  steps:
    - name: Checkout utils-docker-platform repo
      uses: actions/checkout@v4
      with:
        repository: IQGeo/utils-docker-platform
        ref: master
        token: ${{ inputs.gh_token }}

    - name: Checkout Language Packs
      uses: actions/checkout@v4
      with:
        repository: IQGeo/utils-language-packs
        path: utils-language-packs
        token: ${{ inputs.gh_token }}        

    - name: Download binaries artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: platform/7x

    - name: Display downloaded artifacts
      shell: bash
      working-directory: platform/7x
      run: |
        echo "Downloaded artifacts:"
        ls -la
        echo "Checking for IQGeo-Core tar.gz files:"
        ls -la IQGeo-Core-*.tar.gz || echo "No IQGeo-Core tar.gz files found"

    - name: Copy Language Packs from utils-language-packs
      continue-on-error: true
      shell: bash
      run: |
        if [ -z "${{ inputs.shortened_version }}" ]; then
          echo "shortened_version not provided, skipping language pack copy"
          exit 0
        fi
        
        echo "Copying language packs from utils-language-packs for platform"
        pwd
        ls -la
        ls -la utils-language-packs
        ls -la utils-language-packs/Platform || echo "Platform directory not found in language packs"
        echo "Copy Language Packs from utils-language-packs repo"
        if [ -d "utils-language-packs/Platform/${{ inputs.shortened_version }}" ]; then
          cp -RT utils-language-packs/Platform/${{ inputs.shortened_version }}/ platform/7x/languagepacks/
          echo "Language packs copied successfully"
          ls -la platform/7x/languagepacks/
        else
          echo "Language pack directory for platform/${{ inputs.shortened_version }} not found"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ACR
      shell: bash
      run: docker login -u ${{ inputs.registry_username }} -p ${{ inputs.registry_password }} ${{ inputs.acr }}

    - name: Determine architecture tag suffix
      id: arch
      shell: bash
      run: |
        if [ "${{ inputs.platform }}" == "arm64" ]; then
          echo "suffix=arm-64" >> $GITHUB_OUTPUT
        else
          echo "suffix=amd-64" >> $GITHUB_OUTPUT
        fi

    - name: Ensure patches folder exists
      shell: bash
      working-directory: platform/7x
      run: |
        # Create patches directory structure if it doesn't exist
        # This is needed for platform versions 7.2+ which don't have patches
        # Versions 7.0 and 7.1 have patches, but 7.3, 7.4, etc. do not
        mkdir -p patches/${{ inputs.version }}
        echo "Created patches/${{ inputs.version }} directory (if it didn't exist)"

    - name: Determine CONTAINER_REGISTRY build arg
      id: registry
      shell: bash
      run: |
        # For base and base-clear images, use engineering/ path (for platform-prereqs-minimal)
        # For devdb images, use engineering_prefix/ path (for injector and platform images)
        # For other images, use engineering_prefix/ path (for previously built platform images)
        if [ "${{ inputs.image_type }}" == "base" ] || [ "${{ inputs.image_type }}" == "base-clear" ]; then
          echo "value=${{ inputs.acr }}/engineering/" >> $GITHUB_OUTPUT
        else
          echo "value=${{ inputs.acr }}/${{ inputs.engineering_prefix }}/" >> $GITHUB_OUTPUT
        fi
    
    - name: Determine working directory and image name
      id: build_context
      shell: bash
      run: |
        if [ "${{ inputs.docker_context }}" == "deployment-devdb" ]; then
          echo "workdir=deployment-devdb" >> $GITHUB_OUTPUT
          echo "image_name=${{ inputs.acr }}/${{ inputs.engineering_prefix }}/platform-${{ inputs.image_type }}" >> $GITHUB_OUTPUT
        else
          echo "workdir=platform/7x" >> $GITHUB_OUTPUT
          echo "image_name=${{ inputs.acr }}/${{ inputs.engineering_prefix }}/platform/platform-${{ inputs.image_type }}" >> $GITHUB_OUTPUT
        fi

    - name: Build and push platform image
      shell: bash
      working-directory: ${{ steps.build_context.outputs.workdir }}
      run: |
        docker build \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg PLATFORM_VERSION=${{ inputs.version }} \
          --build-arg DEV_TOOLS_VERSION=${{ inputs.dev_tools_version }} \
          --build-arg CONTAINER_REGISTRY=${{ steps.registry.outputs.value }} \
          --build-arg PLATFORM_BASE=${{ inputs.platform_base }} \
          --build-arg OBFUSCATE=${{ inputs.obfuscate }} \
          -f ${{ inputs.dockerfile }} \
          -t ${{ steps.build_context.outputs.image_name }}:${{ inputs.build_id }}_${{ steps.arch.outputs.suffix }} \
          .
        docker push ${{ steps.build_context.outputs.image_name }}:${{ inputs.build_id }}_${{ steps.arch.outputs.suffix }}
